name: Sync Data on Schedule

on:
  schedule:
  - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  sync-data-v0:
    uses: ./.github/workflows/sync.yml
    with:
      api_ref: main
  sync-data-v1:
    uses: ./.github/workflows/sync.yml
    with:
      api_ref: v1
