# Apache License 2.0

name: Sync Data on Schedule

on:
  schedule:
  - cron: '17 * * * *'
  workflow_dispatch:

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: open-space-toolkit-data

jobs:
  prepare-environment:
    name: Prepare Environment Variables
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.project-name.outputs.value }}
      project_version: ${{ steps.project-version.outputs.value }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{ github.ref }}
      - id: project-name
        name: Get Project Name
        run: |
          echo "Project name: ${{ env.PROJECT_NAME }}"
          echo "value=${{ env.PROJECT_NAME }}" >> $GITHUB_OUTPUT
      - id: project-version
        name: Get Project Version
        run: |
          project_version=$(git describe --tags --always)
          echo "Project version: ${project_version}"
          echo "value=${project_version}" >> $GITHUB_OUTPUT

  sync-data-v0:
    name: Data Sync (API V0)
    runs-on: ubuntu-latest
    needs:
      - prepare-environment
    steps:
      - name: Checkout Manifest File
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          sparse-checkout: |
            data/manifest.json
          sparse-checkout-cone-mode: false
      - name: Determine Updates
        run: |
          OUTPUT=$(make determine-updates)
          echo "::set-output name=data::$OUTPUT"
      - name: Checkout Files to Update
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          ref: main
          sparse-checkout: |
            ${{ steps.pull_data.outputs.data }}"
          sparse-checkout-cone-mode: false
      - name: Pull Data
        run: make pull-data
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync data with remote sources"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: git show --name-only

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"


  sync-data-v1:
    name: Data Sync (API V1)
    runs-on: ubuntu-latest
    needs:
      - prepare-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          ref: v1
      - name: Pull Data
        run: make pull-data
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: sync data with remote sources"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: git show --name-only

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
