# Apache License 2.0

name: Sync Data

on:
  workflow_call:
    inputs:
      api_ref:
        description: The branch name to sync.
        required: true
        type: string

concurrency:
  group: main-${{ inputs.api_ref }}
  cancel-in-progress: true

jobs:
  sync-data:
    name: Data Sync ( ${{inputs.api_ref}} )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Manifest File
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{inputs.api_ref}}
          sparse-checkout: |
            data/manifest.json
      - name: Build Docker Image
        run: make build
      - name: Determine Updates
        id: determine_updates
        run: |
          {
            echo 'FILES_TO_UPDATE<<EOF' 
            make determine-updates
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Checkout Files to Update
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          ref: ${{inputs.api_ref}}
          sparse-checkout: |
            ${{ env.FILES_TO_UPDATE }}
          sparse-checkout-cone-mode: false
      - name: List Files
        run: |
          echo "Checked out the following files for update:"
          find data -type f
      - name: Pull Data
        run: make pull-data
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync data with remote sources"
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: git show --name-only
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
