# Apache License 2.0

name: Sync Data with Remote Sources

on:
  schedule:
  - cron: '* * * * *'

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: open-space-toolkit-data

jobs:
  prepare-environment:
    name: Prepare Environment Variables
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.project-name.outputs.value }}
      project_version: ${{ steps.project-version.outputs.value }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - id: project-name
        name: Get Project Name
        run: |
          echo "Project name: ${{ env.PROJECT_NAME }}"
          echo "value=${{ env.PROJECT_NAME }}" >> $GITHUB_OUTPUT
      - id: project-version
        name: Get Project Version
        run: |
          project_version=$(git describe --tags --always)
          echo "Project version: ${project_version}"
          echo "value=${project_version}" >> $GITHUB_OUTPUT

  sync-data:
    name: Sync data with remote sources
    runs-on: ubuntu-latest
    needs:
      - prepare-environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Data
        run: make pull-data
